spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_controledetitulos?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
